export const REQUEST_COURSE = 'REQUEST_COURSE';
export const RECEIVE_COURSE = 'RECEIVE_COURSE';

export const REQUEST_COURSE_GRADES = 'REQUEST_COURSE_GRADES';
export const RECEIVE_COURSE_GRADES = 'RECEIVE_COURSE_GRADES';

export const REQUEST_INSTRUCTOR = 'REQUEST_INSTRUCTOR';
export const RECEIVE_INSTRUCTOR = 'RECEIVE_INSTRUCTOR';